<a href="https://colab.research.google.com/github/Debobrata-Chakraborty-Kakon/Amar_iSchool_internship/blob/main/Coding_Task_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import matplotlib.pyplot as plt



## Sigmoid Activation Function

In [16]:
def sigmoid(X):
   return 1/(1+np.exp(-X))

## Relu Activation Function

In [17]:
def relu(X):
   return np.maximum(0,X)

# X & Y Initialization

In [18]:
X = np.random.randn(2, 3)
print(X)
Y = np.random.randn(1, 3)
print(Y)

[[-1.76018414  1.78320756  0.42732463]
 [ 1.56088478 -0.44842032 -1.64391169]]
[[0.61102213 2.3192029  0.16848785]]


# Layers

In [19]:
n_x=X.shape[0]
n_h=4
n_y=Y.shape[0]

print("The size of the input layer is: n_x = " + str(n_x))
print("The size of the hidden layer is: n_h = " + str(n_h))
print("The size of the output layer is: n_y = " + str(n_y))

The size of the input layer is: n_x = 2
The size of the hidden layer is: n_h = 4
The size of the output layer is: n_y = 1


# Weights and baises

In [20]:
W1=np.random.randn(n_h,n_x) * 0.01
b1=np.zeros((n_h,1))
W2=np.random.randn(n_y,n_h) * 0.01
b2=np.zeros((n_y,1))
    
    

parameters = {"W1": W1,
              "b1": b1,
              "W2": W2,
              "b2": b2}

print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))


W1 = [[ 0.00169266 -0.00329736]
 [-0.00389572  0.01215722]
 [-0.01347648  0.0067537 ]
 [-0.0009804   0.00246381]]
b1 = [[0.]
 [0.]
 [0.]
 [0.]]
W2 = [[-0.00146191 -0.00687526 -0.00710505 -0.00746096]]
b2 = [[0.]]


## Forward Propagation

In [29]:
W1=parameters["W1"]
b1=parameters["b1"]
W2=parameters["W2"]
b2=parameters["b2"]

Z1=np.dot(W1,X)+b1
A1=relu(Z1)
Z2=np.dot(W2,A1)+b2
A2=sigmoid(Z2)

assert(A2.shape == (1, X.shape[1]))
    
forward_prop = {"Z1": Z1,
                "A1": A1,
                "Z2": Z2,
                "A2": A2}
print("A1 = " + str(forward_prop["A1"]))                
print("A2 = " + str(forward_prop["A2"]))

A1 = [[0.         0.00449697 0.00614389]
 [0.02583321 0.         0.        ]
 [0.03426284 0.         0.        ]
 [0.00557141 0.         0.        ]]
A2 = [[0.49988435 0.49999836 0.49999775]]


# Backward Propagation

In [23]:
m = X.shape[1]
m

3

In [26]:
W1=parameters["W1"]
W2=parameters["W2"]

A1=forward_prop["A1"]
A2=forward_prop["A2"]

dZ2 = A2-Y
dW2 = np.dot(dZ2,A1.T)/m
db2 = np.sum(dZ2,axis=1,keepdims=True)/m
dZ1 = np.dot(W2.T,dZ2)*(1 - np.power(A1, 2))
dW1 = np.dot(dZ1,X.T)/m
db1 = np.sum(dZ1,axis=1,keepdims=True)/m

back_prop = { "dW1": dW1,
              "db1": db1,
              "dW2": dW2,
              "db2": db2}

print ("dW1 = "+ str(back_prop["dW1"]))
print ("db1 = "+ str(back_prop["db1"]))
print ("dW2 = "+ str(back_prop["dW2"]))
print ("db2 = "+ str(back_prop["db2"]))

dW1 = [[ 1.41643527e-03 -4.74274329e-05]
 [ 6.66181804e-03 -2.23303365e-04]
 [ 6.88470857e-03 -2.30974891e-04]
 [ 7.22902609e-03 -2.42051967e-04]]
db1 = [[0.00077911]
 [0.00366396]
 [0.00378629]
 [0.00397627]]
dW2 = [[-0.00204805 -0.00095702 -0.0012693  -0.0002064 ]]
db2 = [[-0.53294414]]
